# Form implementation generated from reading ui file 'game_gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainGame(object):
    def setupUi(self, MainGame):
        MainGame.setObjectName("MainGame")
        MainGame.resize(592, 389)
        MainGame.setMinimumSize(QtCore.QSize(592, 389))
        self.centralwidget = QtWidgets.QWidget(parent=MainGame)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.send_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send_btn.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.send_btn.setObjectName("send_btn")
        self.gridLayout.addWidget(self.send_btn, 1, 2, 1, 1)
        self.room_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.room_btn.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.room_btn.setObjectName("room_btn")
        self.gridLayout.addWidget(self.room_btn, 2, 2, 1, 1)
        self.exit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_btn.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout.addWidget(self.exit_btn, 2, 0, 1, 1)
        self.chat_wind = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.chat_wind.setReadOnly(True)
        self.chat_wind.setObjectName("chat_wind")
        self.gridLayout.addWidget(self.chat_wind, 0, 0, 1, 3)
        self.ban_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ban_btn.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.ban_btn.setObjectName("ban_btn")
        self.gridLayout.addWidget(self.ban_btn, 2, 1, 1, 1)
        self.input_chat = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_chat.setObjectName("input_chat")
        self.gridLayout.addWidget(self.input_chat, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainGame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainGame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 18))
        self.menubar.setObjectName("menubar")
        MainGame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainGame)
        self.statusbar.setObjectName("statusbar")
        MainGame.setStatusBar(self.statusbar)

        self.retranslateUi(MainGame)
        QtCore.QMetaObject.connectSlotsByName(MainGame)

    def retranslateUi(self, MainGame):
        _translate = QtCore.QCoreApplication.translate
        MainGame.setWindowTitle(_translate("MainGame", "MainWindow"))
        self.send_btn.setText(_translate("MainGame", "Send"))
        self.room_btn.setText(_translate("MainGame", "Change room"))
        self.exit_btn.setText(_translate("MainGame", "Exit"))
        self.ban_btn.setText(_translate("MainGame", "Ban"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainGame = QtWidgets.QMainWindow()
    ui = Ui_MainGame()
    ui.setupUi(MainGame)
    MainGame.show()
    sys.exit(app.exec())
