# Form implementation generated from reading ui file 'reg_gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainRegistration(object):
    def setupUi(self, MainRegistration):
        MainRegistration.setObjectName("MainRegistration")
        MainRegistration.resize(288, 186)
        MainRegistration.setMinimumSize(QtCore.QSize(288, 186))
        self.centralwidget = QtWidgets.QWidget(parent=MainRegistration)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.name_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 1, 0, 1, 1)
        self.input_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_name.setObjectName("input_name")
        self.gridLayout.addWidget(self.input_name, 2, 0, 1, 1)
        self.reg_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.reg_label.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.reg_label.setObjectName("reg_label")
        self.gridLayout.addWidget(self.reg_label, 0, 0, 1, 1)
        self.check_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.check_btn.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.check_btn.setObjectName("check_btn")
        self.gridLayout.addWidget(self.check_btn, 3, 0, 1, 1)
        self.check_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.check_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.check_label.setText("")
        self.check_label.setObjectName("check_label")
        self.gridLayout.addWidget(self.check_label, 4, 0, 1, 1)
        self.send_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send_btn.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.send_btn.setObjectName("send_btn")
        self.gridLayout.addWidget(self.send_btn, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainRegistration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainRegistration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 288, 18))
        self.menubar.setObjectName("menubar")
        MainRegistration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainRegistration)
        self.statusbar.setObjectName("statusbar")
        MainRegistration.setStatusBar(self.statusbar)

        self.retranslateUi(MainRegistration)
        QtCore.QMetaObject.connectSlotsByName(MainRegistration)

    def retranslateUi(self, MainRegistration):
        _translate = QtCore.QCoreApplication.translate
        MainRegistration.setWindowTitle(_translate("MainRegistration", "MainWindow"))
        self.name_label.setText(_translate("MainRegistration", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-style:italic;\">Enter your name</span></p></body></html>"))
        self.reg_label.setText(_translate("MainRegistration", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">REGISTRATION</span></p></body></html>"))
        self.check_btn.setText(_translate("MainRegistration", "Check name"))
        self.send_btn.setText(_translate("MainRegistration", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainRegistration = QtWidgets.QMainWindow()
    ui = Ui_MainRegistration()
    ui.setupUi(MainRegistration)
    MainRegistration.show()
    sys.exit(app.exec())
