# Form implementation generated from reading ui file 'room_gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainRoom(object):
    def setupUi(self, MainRoom):
        MainRoom.setObjectName("MainRoom")
        MainRoom.resize(272, 200)
        MainRoom.setMinimumSize(QtCore.QSize(272, 200))
        self.centralwidget = QtWidgets.QWidget(parent=MainRoom)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.combo_room = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_room.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.combo_room.setObjectName("combo_room")
        self.gridLayout.addWidget(self.combo_room, 1, 0, 1, 1)
        self.join_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.join_btn.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.join_btn.setObjectName("join_btn")
        self.gridLayout.addWidget(self.join_btn, 4, 0, 1, 1)
        self.choose_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.choose_label.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.choose_label.setObjectName("choose_label")
        self.gridLayout.addWidget(self.choose_label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setStyleSheet("background-color: rgb(255, 85, 127);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainRoom.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainRoom)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 272, 18))
        self.menubar.setObjectName("menubar")
        MainRoom.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainRoom)
        self.statusbar.setObjectName("statusbar")
        MainRoom.setStatusBar(self.statusbar)

        self.retranslateUi(MainRoom)
        QtCore.QMetaObject.connectSlotsByName(MainRoom)

    def retranslateUi(self, MainRoom):
        _translate = QtCore.QCoreApplication.translate
        MainRoom.setWindowTitle(_translate("MainRoom", "MainWindow"))
        self.join_btn.setText(_translate("MainRoom", "Join game"))
        self.choose_label.setText(_translate("MainRoom", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">CHOOSE ROOM</span></p></body></html>"))
        self.pushButton.setText(_translate("MainRoom", "Check room"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainRoom = QtWidgets.QMainWindow()
    ui = Ui_MainRoom()
    ui.setupUi(MainRoom)
    MainRoom.show()
    sys.exit(app.exec())
